name: Variables
on:
  push:
  workflow_dispatch:
env:
  GLOBAL_VAR: "This is a global variable"
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: Echo variables
        env:
          STEP_VAR: "This is a step variable"
          STEP_VAR2: "This is another step variable"
        run: |
          echo "Global variable: ${{env.GLOBAL_VAR}}"
          echo "Job variable: ${{env.JOB_VAR}}"
          echo "Step variable: ${{env.STEP_VAR}}"
          echo "Step variable 2: ${{env.STEP_VAR2}}"
